-- Anatomia 3D - schema inicial (Flyway V1)
-- Segue docs/DATABASE.md e resolve as decisoes pendentes:
--   * nomes alternativos em ALTERNATE_NAME
--   * fonte educacional propria por estrutura (nao reutiliza SOURCE_LICENSE)
--   * estado de publicacao em ANATOMICAL_STRUCTURE.published

CREATE TABLE anatomical_system (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(32)  NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE anatomical_region (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32)  NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE anatomical_structure (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_code            VARCHAR(32)  NOT NULL UNIQUE,
    name                     VARCHAR(160) NOT NULL,
    normalized_name          VARCHAR(160) NOT NULL,
    description              TEXT,
    function_description     TEXT,
    educational_source_name  VARCHAR(160),
    educational_source_url   VARCHAR(500),
    active                   BOOLEAN      NOT NULL DEFAULT true,
    published                BOOLEAN      NOT NULL DEFAULT false,
    system_id                BIGINT       REFERENCES anatomical_system (id),
    region_id                BIGINT       REFERENCES anatomical_region (id),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_structure_normalized_name ON anatomical_structure (normalized_name);
CREATE INDEX idx_structure_system_id        ON anatomical_structure (system_id);
CREATE INDEX idx_structure_region_id        ON anatomical_structure (region_id);
CREATE INDEX idx_structure_external_code    ON anatomical_structure (external_code);

CREATE TABLE alternate_name (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id BIGINT       NOT NULL REFERENCES anatomical_structure (id) ON DELETE CASCADE,
    name         VARCHAR(160) NOT NULL
);

CREATE INDEX idx_alternate_name_structure ON alternate_name (structure_id);

CREATE TABLE structure_relation (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_structure_id   BIGINT       NOT NULL REFERENCES anatomical_structure (id),
    target_structure_id   BIGINT       NOT NULL REFERENCES anatomical_structure (id),
    relation_type         VARCHAR(64)  NOT NULL,
    description           TEXT,
    CONSTRAINT ck_relation_no_self CHECK (source_structure_id <> target_structure_id),
    CONSTRAINT uq_relation_unique
        UNIQUE (source_structure_id, target_structure_id, relation_type)
);

CREATE INDEX idx_relation_source ON structure_relation (source_structure_id);
CREATE INDEX idx_relation_target ON structure_relation (target_structure_id);

CREATE TABLE source_license (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name      VARCHAR(160) NOT NULL UNIQUE,
    author           VARCHAR(160) NOT NULL,
    license_name     VARCHAR(120) NOT NULL,
    license_url      VARCHAR(500),
    attribution_text TEXT,
    source_url       VARCHAR(500)
);

CREATE TABLE asset (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id      BIGINT      NOT NULL REFERENCES anatomical_structure (id),
    file_url          VARCHAR(500) NOT NULL,
    file_format       VARCHAR(16)  NOT NULL,
    checksum          VARCHAR(64)  NOT NULL,
    version           VARCHAR(16)  NOT NULL,
    modifications     TEXT,
    published         BOOLEAN      NOT NULL DEFAULT false,
    source_license_id BIGINT       NOT NULL REFERENCES source_license (id)
);

CREATE INDEX idx_asset_structure ON asset (structure_id);