-- Anatomia 3D - schema de conceitos anatomicos (Flyway V5)
-- Adiciona o nivel de conceito (FMA) que agrupa estruturas, seguindo docs/DATABASE.md e a Decisao D2.
-- * ANATOMICAL_CONCEPT: conceitos termino-anatomicos (external_code = FMA####).
-- * CONCEPT_STRUCTURE: vinculo conceito -> estrutura (muitos-para-muitos).
-- * ANATOMICAL_STRUCTURE.source_id: identificador do asset de origem (FJ####) para rastreabilidade.

ALTER TABLE anatomical_structure ADD COLUMN source_id VARCHAR(32);

CREATE INDEX idx_structure_source_id ON anatomical_structure (source_id);

CREATE TABLE anatomical_concept (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_code      VARCHAR(32)  NOT NULL UNIQUE,
    name               VARCHAR(200) NOT NULL,
    name_pt            VARCHAR(200) NOT NULL,
    normalized_name_pt VARCHAR(200) NOT NULL,
    systems            VARCHAR(255) NOT NULL,
    element_count      INTEGER      NOT NULL,
    name_derived       BOOLEAN      NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_concept_normalized_name_pt ON anatomical_concept (normalized_name_pt);
CREATE INDEX idx_concept_name               ON anatomical_concept (name);

CREATE TABLE concept_structure (
    concept_id   BIGINT NOT NULL REFERENCES anatomical_concept (id)    ON DELETE CASCADE,
    structure_id BIGINT NOT NULL REFERENCES anatomical_structure (id)  ON DELETE CASCADE,
    PRIMARY KEY (concept_id, structure_id)
);

CREATE INDEX idx_concept_structure_structure_id ON concept_structure (structure_id);